(function(g){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var HHa=function(a){a=String(a);var b=a.indexOf(".");-1==b&&(b=a.length);return(0,g.WCa)("0",Math.max(0,2-b))+a},IHa=function(){return{D:"svg",
U:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},S:[{D:"path",U:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.64-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.63 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2z"}}]}},JHa=function(){return{D:"svg",
U:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},S:[{D:"path",U:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.63-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.64 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2zm-2 1H8v-6c0-2.48 1.51-4.5 4-4.5s4 2.02 4 4.5v6z"}}]}},N3=function(a){"number"===typeof a?(this.date=KHa(a,0,1),M3(this,1)):g.Na(a)?(this.date=KHa(a.getFullYear(),a.getMonth(),a.getDate()),M3(this,a.getDate())):(this.date=new Date(g.Sa()),a=this.date.getDate(),
this.date.setHours(0),this.date.setMinutes(0),this.date.setSeconds(0),this.date.setMilliseconds(0),M3(this,a))},KHa=function(a,b,c){b=new Date(a,b,c);
0<=a&&100>a&&b.setFullYear(b.getFullYear()-1900);return b},M3=function(a,b){a.getDate()!=b&&a.date.setUTCHours(a.date.getUTCHours()+(a.getDate()<b?1:-1))},O3=function(a,b){g.MN.call(this,a,{D:"div",
K:"ytp-reminder-menu",U:{role:"menu",tabindex:"-1"},S:[{D:"div",K:"ytp-reminder-menu-contents",S:[{D:"div",K:"ytp-reminder-menu-items"}]}]},100,!0);this.i=b;this.u=[];this.menuPopupRenderer=void 0;this.items=this.ha("ytp-reminder-menu-items");this.hide()},MHa=function(a){var b=LHa(a),c=0,d={};
for(c=0;c<b.length;d={Lv:d.Lv},c++){var e=a.u[c];e||(e=new g.W({D:"div",K:"ytp-reminder-menu-item",U:{role:"menuitem",tabindex:"0"},S:[{D:"div",K:"ytp-reminder-menu-item-icon",ba:"{{icon}}"},{D:"div",K:"ytp-reminder-menu-item-label",ba:"{{text}}"}]}),d.Lv=c,e.ya("click",function(l){return function(){var m=l.Lv;a.jb();m=LHa(a)[m];a.V("reminderMenuItemClicked",m.serviceEndpoint||m.command)}}(d)),e.fa(a.items),a.u[c]=e);
var f=b[c],h=null;switch(f.icon&&f.icon.iconType){case "NOTIFICATIONS":h=IHa();break;case "NOTIFICATIONS_NONE":h=JHa();break;case "NOTIFICATIONS_ACTIVE":h=g.kL()}f=f.text?g.KD(f.text):"";e.update({icon:h,text:f})}for(;c<a.u.length;)a.u.pop().dispose();0===c?a.jb():a.Ec(a.i)},LHa=function(a){return(a.menuPopupRenderer&&a.menuPopupRenderer.items||[]).reduce(function(b,c){c&&c.menuServiceItemRenderer&&b.push(c.menuServiceItemRenderer);
return b},[])},P3=function(a){g.W.call(this,{D:"div",
S:[{D:"button",ka:["ytp-offline-slate-button","ytp-button"],S:[{D:"div",K:"ytp-offline-slate-button-icon",ba:"{{icon}}"},{D:"div",K:"ytp-offline-slate-button-text",ba:"{{text}}"}]}]});this.G=a;this.upcomingEventReminderButtonRenderer=this.toggleButtonRenderer=null;this.l=void 0;this.B=this.i=null;(this.C=this.ha("ytp-offline-slate-button"))&&this.N(this.C,"click",this.I);this.hide()},NHa=function(a,b,c){!a.toggleButtonRenderer&&b&&b.toggleButtonRenderer?a.toggleButtonRenderer=b.toggleButtonRenderer:
b&&b.toggleButtonRenderer||(a.toggleButtonRenderer=null);
!a.upcomingEventReminderButtonRenderer&&c&&c.upcomingEventReminderButtonRenderer?a.upcomingEventReminderButtonRenderer=c.upcomingEventReminderButtonRenderer:c&&c.upcomingEventReminderButtonRenderer||(a.upcomingEventReminderButtonRenderer=null);Q3(a)},Q3=function(a){if(a.toggleButtonRenderer){var b=a.toggleButtonRenderer;
if(b.isToggled){var c=b.toggledText?g.KD(b.toggledText):"";a.update({text:c,icon:R3(b.toggledIcon)})}else c=b.defaultText?g.KD(b.defaultText):"",a.update({text:c,icon:R3(b.defaultIcon)});a.show()}else a.upcomingEventReminderButtonRenderer?(b=OHa(a))?(c=b.text?g.KD(b.text):"",a.update({text:c,icon:R3(b.icon)}),a.show()):a.hide():a.hide()},QHa=function(a,b,c){a.B||(a.B=new g.dt(a.G.T().af));
var d={context:g.Eq(a.B.i||g.Fq())};g.mu()&&(d.context.clientScreenNonce=g.mu());d.params=c;g.Gq(a.B,b,d,{timeout:5E3,onSuccess:function(){a.upcomingEventReminderButtonRenderer&&a.l&&(a.upcomingEventReminderButtonRenderer.currentState=a.l,a.l=void 0)},
onError:function(){PHa(a)},
onTimeout:function(){PHa(a)}})},PHa=function(a){a.toggleButtonRenderer?(a.toggleButtonRenderer.isToggled=!a.toggleButtonRenderer.isToggled,Q3(a)):a.upcomingEventReminderButtonRenderer&&(a.l=void 0,Q3(a))},R3=function(a){if(!a)return null;
switch(a.iconType){case "NOTIFICATIONS":return IHa();case "NOTIFICATIONS_NONE":return JHa();case "NOTIFICATIONS_ACTIVE":return g.kL();default:return null}},OHa=function(a){if(!a.upcomingEventReminderButtonRenderer)return null;
var b=a.l||a.upcomingEventReminderButtonRenderer.currentState;a=g.q(a.upcomingEventReminderButtonRenderer.states||[]);for(var c=a.next();!c.done;c=a.next())if((c=c.value.upcomingEventReminderButtonStateRenderer)&&c.state===b&&c.button&&c.button.buttonRenderer)return c.button.buttonRenderer;return null},S3=function(a){g.W.call(this,{D:"div",
K:"ytp-offline-slate",S:[{D:"div",K:"ytp-offline-slate-background"},{D:"div",K:"ytp-offline-slate-bar",S:[{D:"span",K:"ytp-offline-slate-icon",S:[{D:"svg",U:{fill:"#fff",height:"100%",viewBox:"0 0 24 24",width:"100%"},S:[{D:"path",U:{d:"M16.94 6.91l-1.41 1.45c.9.94 1.46 2.22 1.46 3.64s-.56 2.71-1.46 3.64l1.41 1.45c1.27-1.31 2.05-3.11 2.05-5.09s-.78-3.79-2.05-5.09zM19.77 4l-1.41 1.45C19.98 7.13 21 9.44 21 12.01c0 2.57-1.01 4.88-2.64 6.54l1.4 1.45c2.01-2.04 3.24-4.87 3.24-7.99 0-3.13-1.23-5.96-3.23-8.01zM7.06 6.91c-1.27 1.3-2.05 3.1-2.05 5.09s.78 3.79 2.05 5.09l1.41-1.45c-.9-.94-1.46-2.22-1.46-3.64s.56-2.71 1.46-3.64L7.06 6.91zM5.64 5.45L4.24 4C2.23 6.04 1 8.87 1 11.99c0 3.13 1.23 5.96 3.23 8.01l1.41-1.45C4.02 16.87 3 14.56 3 11.99s1.01-4.88 2.64-6.54z"}},
{D:"circle",U:{cx:"12",cy:"12",r:"3"}}]}]},{D:"span",K:"ytp-offline-slate-messages",S:[{D:"div",K:"ytp-offline-slate-main-text",U:{"aria-label":"{{label}}"},ba:"{{mainText}}"},{D:"div",K:"ytp-offline-slate-subtitle-text",ba:"{{subtitleText}}"}]},{D:"span",K:"ytp-offline-slate-buttons"}]},{D:"button",ka:["ytp-offline-slate-close-button","ytp-button"],S:[g.fL()]},{D:"button",ka:["ytp-offline-slate-open-button","ytp-button"],S:[g.eL()]},{D:"div",K:"ytp-offline-slate-trailer-chip",ba:"Trailer"}]});var b=
this;this.api=a;this.l=this.i=null;this.background=this.ha("ytp-offline-slate-background");this.B=this.ha("ytp-offline-slate-bar");this.C=new g.K(function(){g.N(b.B,"ytp-offline-slate-bar-fade")},15E3);
this.I=!1;this.u=new g.K(function(){g.N(b.element,"ytp-offline-slate-collapsed")},15E3);
g.J(this,this.u);g.J(this,this.C);this.countdownTimer=new g.K(this.CH,1E3,this);this.N(a,"presentingplayerstatechange",this.FH);this.N(a,"livestatedata",this.wa);a=this.ha("ytp-offline-slate-close-button");this.N(a,"click",function(){g.N(b.element,"ytp-offline-slate-collapsed")});
a=this.ha("ytp-offline-slate-open-button");this.N(a,"click",function(){g.mn(b.element,"ytp-offline-slate-collapsed")});
this.hide();a=this.getVideoData();a.getPlayerResponse()&&(a=a.getPlayerResponse().playabilityStatus)&&this.wa(a)},T3=function(a,b,c){var d,e,f,h;
if(b){var l=null!=b.subtitleText?g.KD(b.subtitleText):"";c=c?c:null!=b.mainText?g.KD(b.mainText):"";b=null!==(h=null===(f=null===(e=null===(d=b.mainText)||void 0===d?void 0:d.accessibility)||void 0===e?void 0:e.accessibilityData)||void 0===f?void 0:f.label)&&void 0!==h?h:c;a.update({mainText:c,subtitleText:l,label:b});g.O(a.element,"ytp-offline-slate-single-text-line",!l)}},U3=function(a,b){var c=(0,g.Q)();
this.trigger=a;this.i=b;this.u=c},W3=function(a){g.gN.call(this,a);
var b=this;this.J=!1;this.L=0;this.C=!1;this.l=new g.K(function(){var e=b.player.T(),f=b.getVideoData();if(V3(b))if(RHa(b)){var h;null!==(h=b.heartbeatParams)&&void 0!==h&&h.url&&(e=g.Od(b.heartbeatParams.url,{request_id:g.eu()}),f.la&&(e=g.Od(e,{vvt:f.la}),f.mdxEnvironment&&(e=g.Od(e,{mdx_environment:f.mdxEnvironment}))),f.oauthToken&&(e=g.Od(e,{access_token:f.oauthToken})),SHa(b,f,e))}else THa(b,e,f)},0);
this.i=this.heartbeatParams=null;this.B=!1;this.I=new g.yn(1E3,6E4,1);this.sequenceNumber=0;this.offlineSlate=null;this.W=new g.dt(void 0);this.utcOffsetMinutes=-(new N3).date.getTimezoneOffset();this.u=new g.ZM(this);g.J(this,this.l);g.J(this,this.u);UHa(this);this.u.N(a,"heartbeatparams",this.OJ);this.u.N(a,"presentingplayerstatechange",this.PJ);this.u.N(a,"videoplayerreset",this.QJ);this.u.N(a,g.DD("heartbeat"),this.Bd);this.B&&this.i&&VHa(this,this.i);var c=new g.AD(1E3,0x7ffffffffffff,{priority:0,
namespace:"heartbeat"}),d=new g.AD(0x8000000000000,0x8000000000000,{id:"stream_end",priority:0,namespace:"heartbeat"});a.ud([c,d])},RHa=function(a){var b=a.getVideoData();
return!g.$H(a.getVideoData())||b.WB?!1:b.useInnertubeDrmService()&&b.I?(a="playready"===b.I.flavor&&b.Z("html5_innertube_heartbeats_for_playready"),b="widevine"===b.I.flavor&&b.Z("html5_innertube_heartbeats_for_widevine"),!(a||b)):!0},X3=function(a){return RHa(a)?!!a.heartbeatParams:!!a.getVideoData().heartbeatToken},Y3=function(a,b){if(!a.l.isActive()&&a.J){var c=a.getVideoData();
if(X3(a)||c.isLivePlayback){if(void 0===b){if(a.C){var d;c=a.B?7500:(null===(d=a.heartbeatParams)||void 0===d?0:d.interval)?1E3*a.heartbeatParams.interval:a.getVideoData().XA||6E4}else c=1E3;b=c}a.l.start(b)}}},SHa=function(a,b,c){b.Uh&&(c=g.Od(c,{internalipoverride:b.Uh}));
var d={cpn:b.clientPlaybackNonce};b.contextParams&&(d.context_params=b.contextParams);b.Va&&(d.kpt=b.Va);c=g.Od(c,d);g.Up(c,{format:"RAW",method:"GET",timeout:3E4,onSuccess:function(e){if(!a.l.isActive()&&V3(a)){a.I.reset();a.sequenceNumber++;e=e.responseText;var f=WHa(e);if(f){a.player.xa("onHeartbeat",f);var h="ok"===f.status?f.stop_heartbeat?2:0:"stop"===f.status?1:"live_stream_offline"===f.status?0:-1}else h=(h=e.match(XHa))?"0"===h[1]?0:1:-1;YHa(a,f,e,h)}},
onError:function(e){V3(a)&&Z3(a,!0,"net-"+e.status)},
onTimeout:function(){V3(a)&&Z3(a,!0,"timeout")},
withCredentials:!0})},V3=function(a){var b=a.getVideoData();
return 3===a.player.getPresentingPlayerType()||g.V(a.player.Wa(a.getPlayerType()),4)?!1:X3(a)||b.isLivePlayback?!0:($3(a),!1)},THa=function(a,b,c){var d,e={videoId:c.videoId,
sequenceNumber:a.sequenceNumber,heartbeatServerData:c.heartbeatServerData},f=g.zM(c),h=null!==(d=f.client)&&void 0!==d?d:{};h.utcOffsetMinutes=a.utcOffsetMinutes;e.context=f;e.cpn=c.clientPlaybackNonce;if(f="undefined"!==typeof Intl?(new Intl.DateTimeFormat).resolvedOptions().timeZone:null)h.timeZone=f;h={heartbeatChecks:[]};if(f=c.getPlayerResponse())c.heartbeatToken&&(e.heartbeatToken=c.heartbeatToken),(f=f.playabilityStatus)&&(f=f.liveStreamability)&&f.liveStreamabilityRenderer&&h.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_LIVE_STREAM_STATUS");
c.heartbeatToken&&h.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_YPC");g.wG(b)&&(h.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_UNPLUGGED"),(b=a.player.getProgressState(a.getPlayerType()).ingestionTime)&&isFinite(b)&&(f={},f.clientPlayerPositionUtcMillis=""+Math.floor(1E3*b),h.unpluggedParams=f));e.heartbeatRequestParams=h;b={timeout:3E4,onSuccess:function(l){if(!a.l.isActive()&&V3(a)){var m=l.playabilityStatus,n=JSON.stringify(m)||"{}",p=-1,r=l.playabilityStatus;r&&(a.player.xa("onHeartbeat",r),"OK"===
r.status?p=l.stopHeartbeat?2:0:"UNPLAYABLE"===r.status?p=1:"LIVE_STREAM_OFFLINE"===r.status&&(p=0));l=p;a.sequenceNumber&&-1===l||a.I.reset();a.sequenceNumber++;YHa(a,m,n,l)}},
onError:function(l){V3(a)&&Z3(a,!0,"net-"+l.status)},
onTimeout:function(){V3(a)&&Z3(a,!0,"timeout")}};
g.pI(c)&&(b.wC="Bearer "+g.pI(c));g.Gq(a.W,"player/heartbeat",e,b)},YHa=function(a,b,c,d){-1===d?(b="decode "+g.tf(c),Z3(a,!1,b)):2===d?($3(a),a.C=!0):(a.L=0,a.l.stop(),1===d?(a.C=!1,a.player.Nf("heartbeat.stop",a.Je(c)),g.Sr("heartbeatActionPlayerHalted",ZHa(b))):(a.C=!0,c=0,a.B&&b&&(c=VHa(a,b),a.player.V("livestatedata",b)),c?Y3(a,c):Y3(a)))},VHa=function(a,b){var c,d,e=b.liveStreamability&&b.liveStreamability.liveStreamabilityRenderer,f=!(!e||!e.switchStreamsImmediately),h=$Ha(e),l=a.getVideoData(),
m=a.player.Wa(a.getPlayerType()),n=m.Mb()&&!g.dI(l)&&!a.player.isAtLiveHead(a.getPlayerType());
if(g.RH(l)){var p=(null===(c=a.player.dd())||void 0===c?void 0:c.kb())||{};p.status=b.status||"";p.dvr=""+ +n;p["switch"]=""+ +f;a.player.Fa("heartbeat",g.MA(p))}if(n&&!f)return h;f=e&&e.streamTransitionEndpoint&&e.streamTransitionEndpoint.watchEndpoint;if("STREAM_TRANSITION_TIMING_AT_STREAM_END"===(e&&e.transitionTiming))a.getVideoData().LE=f;else{if(n=f)(n=f&&f.videoId)?(a.player.Ii(n,void 0,void 0,!0,!0,f),a.pu("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT",
b),n=!0):n=!1;if(n)return h}if("OK"===b.status.toUpperCase()){f=e&&e.broadcastId;n=a.i&&a.i.liveStreamability&&a.i.liveStreamability.liveStreamabilityRenderer&&a.i.liveStreamability.liveStreamabilityRenderer.broadcastId;p=f!==n&&(null!=f||a.player.Z("web_player_heartbeat_undefined_killswitch"));if(!l.hlsvp&&!l.ea||p)return e={video_id:l.videoId},l.Hw&&(e.is_live_destination="1"),a.player.Z("web_player_heartbeat_request_watch_next")||(e.disable_watch_next=!0,e.raw_watch_next_response=l.watchNextResponse),
e.autonav_state=l.autonavState,e.oauth_token=l.oauthToken,e.wh=l.wh,8===a.player.getPresentingPlayerType()&&a.player.Rl(8),m=void 0,l.hlsvp||l.ea?p&&(m=new U3("broadcastIdChanged",n+","+f),a.pu("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_BROADCAST_ID_CHANGED",b)):(f&&(m=new U3("formatsReceived",""+f)),a.pu("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_LIVE_STREAM_WENT_ONLINE",b)),a.player.loadVideoByPlayerVars(e,void 0,void 0,void 0,m),h;a.player.kd("heartbeat",
a.getPlayerType())}e&&e.displayEndscreen&&(a.offlineSlate?(l=a.offlineSlate,l.I=!0,l.ab&&l.api.Gn()):g.lK(m)&&(l=(null===(d=a.player.dd())||void 0===d?void 0:d.kb())||{},a.player.Fa("hbse",g.MA(l),!0),a.player.Gn(),a.player.xa("onLiveMediaEnded",b)));return h},$Ha=function(a){var b=0;
a&&a.pollDelayMs&&(a=Number(a.pollDelayMs))&&(b=a);return b},Z3=function(a,b,c){if(!a.l.isActive()){a.l.stop();
a.L++;var d=a.getVideoData();if(d.ZA||b&&!g.$H(a.getVideoData())&&!X3(a)&&d.isLivePlayback)var e=!1;else{var f;(null===(e=a.heartbeatParams)||void 0===e?0:e.Tr)?f=a.heartbeatParams.Tr:f=d.YA||5;e=a.L>=f}e?(b?(b="heartbeat.net",e={enforcedPolicyToHaltOnNetworkFailure:!0}):(b="heartbeat.servererror",e=ZHa()),g.Sr("heartbeatActionPlayerHalted",e),(e=a.getVideoData())&&e.isLivePlayback?a.player.Nf(b,"Video playback interrupted. Please try again.",c):a.player.Nf(b,"Sorry, there was an error licensing this video.",
c)):(Y3(a,a.I.getValue()),g.zn(a.I))}},ZHa=function(a){var b={enforcedPolicyToHaltOnNetworkFailure:!1};
a&&(b.serializedServerContext=a.additionalLoggingData);return b},$3=function(a){a.L=0;
a.l.stop();a.C=!1;a.sequenceNumber=0},UHa=function(a){var b,c=a.getVideoData(),d=a.player.T();
if(c.isLivePlayback)if(g.AF(d.B)){a.B=!0;a.J=!0;if(!g.jG(d)||g.wG(d))a.offlineSlate=new S3(a.player),g.J(a,a.offlineSlate),g.XM(a.player,a.offlineSlate.element,4);(c=c.getPlayerResponse())&&c.playabilityStatus&&(a.i=c.playabilityStatus);if("UNPLAYABLE"!==(null===(b=a.i)||void 0===b?void 0:b.status)||a.player.Z("stop_heartbeat_on_unplayable_live_videos_killswitch"))a.i?(c=$Ha(a.i.liveStreamability&&a.i.liveStreamability.liveStreamabilityRenderer))?Y3(a,c):Y3(a,7500):Y3(a,1E3)}else a.player.Nf("html5.unsupportedlive",
"HTML5_NO_AVAILABLE_FORMATS_FALLBACK","nolive.1");else!g.T(d.experiments,"html5_release_post_live_heartbeat_killswitch")&&g.fb(c.X,"heartbeat")&&a.player.kd("heartbeat",a.getPlayerType())},WHa=function(a){try{var b=JSON.parse(a);
return null!=b?b:void 0}catch(c){}},aIa={ERAS:["BC",
"AD"],ERANAMES:["Before Christ","Anno Domini"],NARROWMONTHS:"JFMAMJJASOND".split(""),STANDALONENARROWMONTHS:"JFMAMJJASOND".split(""),MONTHS:"January February March April May June July August September October November December".split(" "),STANDALONEMONTHS:"January February March April May June July August September October November December".split(" "),SHORTMONTHS:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),STANDALONESHORTMONTHS:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),
WEEKDAYS:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),STANDALONEWEEKDAYS:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),SHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),STANDALONESHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),NARROWWEEKDAYS:"SMTWTFS".split(""),STANDALONENARROWWEEKDAYS:"SMTWTFS".split(""),SHORTQUARTERS:["Q1","Q2","Q3","Q4"],QUARTERS:["1st quarter","2nd quarter","3rd quarter","4th quarter"],AMPMS:["AM","PM"],DATEFORMATS:["EEEE, MMMM d, y",
"MMMM d, y","MMM d, y","M/d/yy"],TIMEFORMATS:["h:mm:ss a zzzz","h:mm:ss a z","h:mm:ss a","h:mm a"],DATETIMEFORMATS:["{1} 'at' {0}","{1} 'at' {0}","{1}, {0}","{1}, {0}"],FIRSTDAYOFWEEK:6,WEEKENDRANGE:[5,6],FIRSTWEEKCUTOFFDAY:5},a4=aIa;a4=aIa;g.k=N3.prototype;g.k.pD=a4.FIRSTDAYOFWEEK;g.k.rD=a4.FIRSTWEEKCUTOFFDAY;g.k.clone=function(){var a=new N3(this.date);a.pD=this.pD;a.rD=this.rD;return a};
g.k.getFullYear=function(){return this.date.getFullYear()};
g.k.getMonth=function(){return this.date.getMonth()};
g.k.getDate=function(){return this.date.getDate()};
g.k.set=function(a){this.date=new Date(a.getFullYear(),a.getMonth(),a.getDate())};
g.k.add=function(a){if(a.l||a.i){var b=this.getMonth()+a.i+12*a.l,c=this.getFullYear()+Math.floor(b/12);b%=12;0>b&&(b+=12);a:{switch(b){case 1:var d=0!=c%4||0==c%100&&0!=c%400?28:29;break a;case 5:case 8:case 10:case 3:d=30;break a}d=31}d=Math.min(d,this.getDate());this.date.setDate(1);this.date.setFullYear(c);this.date.setMonth(b);this.date.setDate(d)}a.days&&(a=new Date((new Date(this.getFullYear(),this.getMonth(),this.getDate(),12)).getTime()+864E5*a.days),this.date.setDate(1),this.date.setFullYear(a.getFullYear()),
this.date.setMonth(a.getMonth()),this.date.setDate(a.getDate()),M3(this,a.getDate()))};
g.k.toString=function(){return[this.getFullYear(),HHa(this.getMonth()+1),HHa(this.getDate())].join("")+""};
g.k.valueOf=function(){return this.date.valueOf()};g.u(O3,g.MN);O3.prototype.hide=function(){this.i&&this.i.removeAttribute("aria-haspopup");g.MN.prototype.hide.call(this)};
O3.prototype.show=function(){this.i&&this.i.setAttribute("aria-haspopup","true");g.MN.prototype.show.call(this)};
O3.prototype.da=function(){g.Fi(this.u);g.MN.prototype.da.call(this)};g.u(P3,g.W);
P3.prototype.I=function(){if(this.toggleButtonRenderer){var a=this.toggleButtonRenderer;a.isToggled?this.u(a.toggledServiceEndpoint):this.u(a.defaultServiceEndpoint);a.isToggled=!a.isToggled;Q3(this)}else if(this.upcomingEventReminderButtonRenderer)if(this.i&&this.i.ab)this.i.jb();else{var b=OHa(this);b&&this.u(b.serviceEndpoint||b.command);b=g.q(b&&b.command&&b.command.commandExecutorCommand&&b.command.commandExecutorCommand.commands||[]);for(var c=b.next();!c.done;c=b.next())if((c=c.value)&&c.openPopupAction&&
c.openPopupAction.popup&&c.openPopupAction.popup.menuPopupRenderer){a=c.openPopupAction.popup.menuPopupRenderer;break}this.i||(this.i=new O3(this.G,this.C),this.i.fa(this.element),g.J(this,this.i),this.i.subscribe("reminderMenuItemClicked",this.u,this));b=this.i;b.menuPopupRenderer=a;MHa(b)}};
P3.prototype.u=function(a){if(a&&(a.addUpcomingEventReminderEndpoint||a.removeUpcomingEventReminderEndpoint)){if(a.addUpcomingEventReminderEndpoint){var b=a.addUpcomingEventReminderEndpoint;var c="notification/add_upcoming_event_reminder"}else a.removeUpcomingEventReminderEndpoint&&(b=a.removeUpcomingEventReminderEndpoint,c="notification/remove_upcoming_event_reminder");if(c&&b&&b.params)for(QHa(this,c,b.params),a=g.q(b.commands||[]),b=a.next();!b.done;b=a.next())if((b=b.value)&&b.updateUpcomingEventReminderButtonStateCommand){this.l=
b.updateUpcomingEventReminderButtonStateCommand.state;Q3(this);break}}};g.u(S3,g.W);g.k=S3.prototype;g.k.getPlayerType=function(){if(8===this.api.getPresentingPlayerType())return 1};
g.k.getVideoData=function(){return this.api.getVideoData(this.getPlayerType())};
g.k.wa=function(a){var b=a&&a.liveStreamability&&a.liveStreamability.liveStreamabilityRenderer.offlineSlate;if(b){this.i=a;b=b.liveStreamOfflineSlateRenderer;b.canShowCountdown?this.CH():T3(this,b);var c=a&&a.liveStreamability&&a.liveStreamability.liveStreamabilityRenderer&&a.liveStreamability.liveStreamabilityRenderer.offlineSlate&&a.liveStreamability.liveStreamabilityRenderer.offlineSlate.liveStreamOfflineSlateRenderer&&a.liveStreamability.liveStreamabilityRenderer.offlineSlate.liveStreamOfflineSlateRenderer.thumbnail;
if(c){var d=0,e=null;c=c.thumbnails;for(var f=0;f<c.length;f++)c[f].width>d&&(d=c[f].width||0,e=c[f].url);e&&(this.background.style.backgroundImage="url("+e+")")}else this.background.style.backgroundImage="";b.actionButtons||b.reminderButton?(this.l||(this.l=new P3(this.api),this.l.fa(this.ha("ytp-offline-slate-buttons")),g.J(this,this.l)),NHa(this.l,b.actionButtons&&b.actionButtons[0],b.reminderButton)):this.l&&NHa(this.l,null,null);this.i=a}else this.i=null;this.FH()};
g.k.FH=function(a){if(8===this.api.getPresentingPlayerType())var b=!0;else{var c=this.api.Wa(),d=this.getVideoData();b=d.isLivePlayback&&(g.lK(c)||g.V(c,2)||g.V(c,64));var e=2===d.autonavState&&g.V(c,2);c=c.Mb()&&!g.dI(d)&&!this.api.isAtLiveHead(void 0,!0);b=b&&!c&&!e}b&&this.i?this.ab?a&&g.kJ(a,2)&&(g.mn(this.element,"ytp-offline-slate-collapsed"),this.u.stop(),g.mn(this.B,"ytp-offline-slate-bar-fade"),this.C.start()):(a=8===this.api.getPresentingPlayerType(),g.O(this.element,"ytp-offline-slate-premiere-trailer",
a),this.show(),this.u.start(),this.api.V("offlineslatestatechange"),this.I&&this.api.Gn()):this.ab&&(this.hide(),this.api.V("offlineslatestatechange"))};
g.k.CH=function(){var a=this.i&&this.i.liveStreamability&&this.i.liveStreamability.liveStreamabilityRenderer&&this.i.liveStreamability.liveStreamabilityRenderer.offlineSlate&&this.i.liveStreamability.liveStreamabilityRenderer.offlineSlate.liveStreamOfflineSlateRenderer;if(a){var b=Math.floor(g.Sa()/1E3),c=a.canShowCountdown&&Number(a.scheduledStartTime);!c||c<=b?(T3(this,a),this.countdownTimer.stop()):(b=g.GL(c-b),T3(this,a,b),g.en(this.countdownTimer))}};
g.k.da=function(){this.countdownTimer.dispose();this.countdownTimer=null;g.W.prototype.da.call(this)};U3.prototype.l=function(a){return this.trigger&&a.trigger?this.trigger===a.trigger&&this.i===a.i:!1};
U3.prototype.isExpired=function(){return 6E4<(0,g.Q)()-this.u};
U3.prototype.toString=function(){return"heartbeat:"+this.trigger+":"+this.i};g.u(W3,g.gN);g.k=W3.prototype;g.k.da=function(){$3(this);this.player.Re("heartbeat");g.gN.prototype.da.call(this)};
g.k.Bd=function(){this.J=!0;Y3(this,2E3)};
g.k.OJ=function(a){this.heartbeatParams=a;Y3(this,2E3)};
g.k.PJ=function(a){var b;8===this.player.getPresentingPlayerType()||"UNPLAYABLE"===(null===(b=this.i)||void 0===b?void 0:b.status)&&!this.player.Z("stop_heartbeat_on_unplayable_live_videos_killswitch")||(g.V(a.state,2)||g.V(a.state,64)?($3(this),this.B&&(this.J=!0,Y3(this,1E3))):(g.V(a.state,1)||g.V(a.state,8))&&Y3(this,2E3))};
g.k.QJ=function(){3!==this.player.getPresentingPlayerType()&&Y3(this,2E3)};
g.k.getPlayerType=function(){if(8===this.player.getPresentingPlayerType())return 1};
g.k.getVideoData=function(){return this.player.getVideoData(this.getPlayerType())};
g.k.Ai=function(a){switch(a){case 4:case 3:return!1}return!0};
g.k.pu=function(a,b,c){a={trigger:a,reason:b};c&&(a.serializedServerContext=c.additionalLoggingData);g.Sr("heartbeatActionPlayerTransitioned",a)};
g.k.Je=function(a){var b="LICENSE",c=WHa(a);if(c)return c.reason||g.GN[b]||"";(a=a.match(XHa))&&(a=Number(a[1]))&&(b=g.Cka(a));return g.GN[b]||""};
g.k.rr=function(){return!!this.offlineSlate&&this.offlineSlate.ab};
var XHa=/^GLS\/1.0 (\d+) (\w+).*?\r\n\r\n([\S\s]*)$/;g.mN.heartbeat=W3;})(_yt_player);
